POST http://localhost:3000/mineBlock
Content-Type: application/json

{
    "data": "First"
}

###


POST http://localhost:3000/addPeer
Content-Type: application/json

{
    "peer": "ws://localhost:4001"
}

###

GET http://localhost:3000/blocks